### ISSUE TITLE
Contentpage: add support for local and global contentblocks

### ISSUE THREAD

**Issue by potzenheimer** [a25kk/aha#3]
In order to provide custom news/job and subcontent listings we need to provide a basic `contentblock` subtype that can be added to a global selectable location or directly to the target contentpage instance.

Rebuild listing template order also to match common layout requirements

**Comment by potzenheimer** [comment]
**New estimation: 6 hours.**
Potential issues steaming from the retrofitting could cause additional troubles. This is a critical enhancement and potentially dangerous.

**Comment by kreativkombinat** [comment]
Layout sollte auch noch angepasst werden, so das bildblock immer raum/licht in der mitte zwischen textblock und sidebar erscheint.

**Comment by potzenheimer** [comment]
**New estimation: 6 hours.**
Das ist jetzt aber andersherum hier und sieht auch so gewollt aus: http://aha360.com/raum/konzeption

**Comment by kreativkombinat** [comment]
Ja genau, so war das auch gewoolt, jetzt würden die Herren Designer das gerne in der mitte haben.

**Comment by potzenheimer** [comment]
Content sections sind nun hinzufügbar und sollten bereits komplett im CMS eingebunden sein.
