### ISSUE TITLE
Paradoxon: Projektübersichtsausschluss

### ISSUE THREAD

**Issue by bumblebee831** [a25kk/aha#5]
Die Funktion 'Display = Von Übersicht ausschließen' bewirkt, dass das betroffene Projekt nicht nur in der Gesamtübersicht aller Projekte (z.B. http://aha360.com/raum/projekte) entfernt wird, sondern auch in der Kategorieübersicht (z.B. http://aha360.com/raum/projekte/baeckerei-konditorei). Somit ist das Projekt zur Gänze nicht mehr erreichbar, was natürlich etwas sinnlos ist. Die Ausschlussfunktion müsste demnach nur für die Gesamtübersicht gelten.

**Comment by potzenheimer** [comment]
Query muss erweitert werden:
`list(self.get_projects(obj))` -> `list(self.get_projects(obj, preview=true/false))`

**Comment by potzenheimer** [comment]
SOllte mit dd7c58c4789d655737d9476ff75aabac12a3400f Christoph Boehner committed 34 seconds ago gefixed sein. Muss aber nochmal getestet werden.

**Comment by potzenheimer** [comment]
Die IMplementierung wurde nun via `**kwargs` durchgeführt, so dass ein Update der Query möglich sein sollte
